### ISSUE TITLE
Error using strrep

### ISSUE THREAD

**Issue by Elkoumy** [jseoane/FSMKL#1]
Hello Jose,
I am trying to use the FSMKL on matlab 2013 and I am facing a problem.
A screen shot of the error is attached.
![matlab r2013a](https://cloud.githubusercontent.com/assets/7217325/13372098/1aa39916-dd41-11e5-841e-5b4cdb990b74.jpg)

The problem is as follow:

> PathwaySelectionFSMKL_main
> Elapsed time is 13.855889 seconds.
> Elapsed time is 9.111274 seconds.
> Error using strrep
> Input strings must have one row.

Error in vectorize (line 22)
    v = strrep(v,'_','._');

Error in build_efficientKEFF (line 38)
        Kse.data(:,j) = vectorize(Ks(j).minik);

Error in mklkernelEff (line 64)
    K = build_efficientKEFF(keff.data);

Error in PathwaySelectionFSMKL_main (line 381)
    K=mklkernelEff(xapp,InfoKernel,Weight,options);

Regards,
Gamal Elkomy

**Comment by jseoane** [comment]
Hi Gamal,

This algorithm uses a different version of the "vectorize" function from
Matlab. The exception that you post shows that you are trying to use the
native matlab vectorize version.
Please, be sure that you are including in your project the libraries
"vectorize" and "devectorize" included in the git for your specific OS.

Hope it helps.

Best,
JA

2016-02-27 0:59 GMT-08:00 Jamal notifications@github.com:

**Comment by Elkoumy** [comment]
Hello Jose,
Thank you for your support.
It works now very well. Please note that the file "costsvmclass.m" is missing, I found it in the SimpleMKL and now it works very well.
Regards,
GK.

**Comment by Elkoumy** [comment]
Hello Jose,
I am dealing with the METABRIC data set and I am facing a problem with preprocessing the clinical data. Is there any standard way to preprocess the Aperio images?

Regards,
J

**Comment by jseoane** [comment]
Hi Jamal,

I have really no experience working with METABRIC images, but we have apply
FSMKL recently to other kind of images (2D electrophoresis gels) and we
have very good results using images textures from Mazda. This is the URL of
the paper http://www.nature.com/articles/srep19256.
Basically we use separate kernels for each features group. Not sure how
well this will work with METABRIC images.

Here a couple of papers on this topic, from METABRIC images:
http://rsos.royalsocietypublishing.org/content/3/2/140501.full
http://stm.sciencemag.org/content/4/157/157ra143.full

Hope it helps.

Best,
JA

2016-06-01 10:01 GMT-07:00 Jamal notifications@github.com:

**Comment by Elkoumy** [comment]
Hello Jose,
Thank you for your reply.
I am trying to apply FSMKL on the METABRIC data set. I have downloaded the data and it is raw data (CEL files , IDAT, Locs,...). Now I am performing preprocessing and normalization.
Is there any way to get the processed data after normalization as the dream competition offered a framework and now it is not available?
Regards,
JK

**Comment by Elkoumy** [comment]
HelloJose, 
Please reply. I really need this.
Regards,
J

**Comment by jseoane** [comment]
Hi Jamal,

I don't think that this is the right forum to speak about METABRIC dataset.
Please use this threat for FSMKL questions only.

You have the methods for preprocessing metabric data in here:
http://www.nature.com/nature/journal/v486/n7403/full/nature10983.html

You can get original METABRIC dream competition data from here:
https://www.synapse.org/#!Synapse:syn1688369/wiki/27311
following the instructions to gain access.

Best,
JA

2016-06-04 2:55 GMT-07:00 Jamal notifications@github.com:

**Comment by gamalelkomy** [comment]
Hello Jose,
I hope you are in a good health.
Could you please tell how to get the relation between a gene , a pathway, and the probe value in your data set called pathway_exp?
Thanks in advance.
Regards,
G. Elkomy
